-- workspace pills only exist when aerospace is the WM (settings.tiling is
-- generated by rice.nix's `tiling` toggle) — without it every pill would
-- shell out to a dead aerospace CLI
if require("settings").tiling then
  require("items.workspaces")
end
require("items.front_app")
require("items.widgets")
