version: '3'
# Set the default task to help (mimicking the Makefile default goal)
tasks:

  dotbot:setup:
    desc: "Initialize dotbot submodule"
    cmds:
    - git submodule update --init --recursive

  select-profiles:
    desc: "Select profiles to install"
    interactive: true
    sources: [ './profiles/*.yaml' ]
    generates: [ 'install.conf.yaml' ]
    cmds:
    # Check for fuzyf otherwise use default
    - ./etc/scripts/select_profiles.sh
    # cmds:
    # - echo "Select profiles to install:"
    # - echo "1. base"
    # - echo "2. catalyst-sops"
    # - echo "3. all"
    # - read -p "Enter your choice (1/2/3): " choice
    # - |
    #   case $choice in
    #     1) echo "base" > .selected_profiles ;;
    #     2) echo "catalyst-sops" > .selected_profiles ;;
    #     3) echo "all" > .selected_profiles ;;
    #     *) echo "Invalid choice. Exiting." && exit 1 ;;
    #   esac

  install:
    deps:
    - dotbot:setup
    - select-profiles
    desc: "Install dotfiles using dotbot"
    cmds:
    - ./install

  clean:
    desc: "Remove the dot file symlinks"
    prompt: "are you sure you want to remove the dead symlinks in your ~ ?!"
    silent: false
    cmds:
    - "echo 'Remove dot files in your home directory...'"
    - "gfind ~ -maxdepth 1 -xtype l -delete -print"
    - "gfind ~/bin -maxdepth 1 -xtype l -delete -print"

  brew:dump:
    desc: "Dump brew packages to Brewfile"
    cmds:
    - brew bundle dump --force --file=./Brewfile
  # Old Stuff Below Still to be fully ported
  # all:
  #   desc: "Run brew, install, asdf, and afx tasks"
  #   deps:
  #   - brew
  #   - install
  #   - asdf
  #   - afx
  #   # Run dependencies sequentially (as in Makefile)
  #   parallel: false

  # k8:
  #   desc: "maybe use helmfile???"
  #   cmds:
  #   - cask install --cask docker
  #   - brew install minikube
  #   - brew install helm
  #   - brew install kubectl
  #   - brew install kubectx

  # afx:
  #   desc: "Install babarot/afx"
  #   cmds:
  #   - curl -sL https://raw.githubusercontent.com/babarot/afx/HEAD/hack/install | sh
  #   - echo 'Done. Run "afx install" next.'

  # brew:
  #   desc: "Install brew and run brew bundle"
  #   cmds:
  #   - sh ./etc/scripts/brew.sh
  #   - brew bundle
  #   - echo 'Done. For saving your brew packages added newly, run "brew bundle dump".'
