# neovim — NvChad v2.5, fully nix-native. NvChad is "just a plugin", but its
# payload is a lazy.nvim spec collection (import = "nvchad.plugins"), so lazy
# stays as the orchestrator: every plugin below feeds lazy's dev.path from
# nixpkgs and all of lazy's network paths are disabled (see lua/configs/lazy.lua
# in ./nvim). The nixpkgs pin replaces lazy-lock.json entirely.
{ pkgs, lib, ... }:

let
  # lazy resolves each spec to <dev.path>/<short-name>, where short-name is the
  # last segment of the spec's repo URL — case included ("NvChad", "LuaSnip").
  # Keys must cover every spec NvChad imports plus lazy's spec for itself; a
  # missing key surfaces as "plugin not installed" at startup, never a clone.
  # nixpkgs' nvchad still declares nvim-treesitter-legacy as a dependency
  # (deprecated, becomes an eval ERROR in 26.11). Runtime plugins come from
  # lazy's dev.path below — the nix-level dep list only shapes the closure —
  # so restate it with main-branch treesitter. Don't reference
  # old.dependencies here: forcing it would evaluate the legacy attr and
  # re-emit the warning this exists to kill.
  nvchadFixed = pkgs.vimPlugins.nvchad.overrideAttrs (_: {
    dependencies = with pkgs.vimPlugins; [
      gitsigns-nvim
      luasnip
      mason-nvim
      nvim-cmp
      nvim-lspconfig
      telescope-nvim
      nvim-treesitter
      nvchad-ui
    ];
  });

  plugins = with pkgs.vimPlugins; {
    "lazy.nvim" = lazy-nvim;
    "NvChad" = nvchadFixed;
    "plenary.nvim" = plenary-nvim;
    "base46" = base46;
    "ui" = nvchad-ui;
    "volt" = nvzone-volt;
    "menu" = nvzone-menu;
    "minty" = nvzone-minty;
    "nvim-web-devicons" = nvim-web-devicons;
    "indent-blankline.nvim" = indent-blankline-nvim;
    "nvim-tree.lua" = nvim-tree-lua;
    "which-key.nvim" = which-key-nvim;
    "conform.nvim" = conform-nvim;
    "gitsigns.nvim" = gitsigns-nvim;
    "mason.nvim" = mason-nvim; # inert: LSPs/formatters come from nix, not :Mason
    "nvim-lspconfig" = nvim-lspconfig;
    "nvim-cmp" = nvim-cmp;
    "LuaSnip" = luasnip;
    "friendly-snippets" = friendly-snippets;
    "nvim-autopairs" = nvim-autopairs;
    "cmp_luasnip" = cmp_luasnip;
    "cmp-nvim-lua" = cmp-nvim-lua;
    "cmp-nvim-lsp" = cmp-nvim-lsp;
    "cmp-buffer" = cmp-buffer;
    # NvChad specs this one as a full codeberg URL; cover both name spellings
    # in case lazy keeps the ".git" suffix when deriving the dir name.
    "cmp-async-path" = cmp-async-path;
    "cmp-async-path.git" = cmp-async-path;
    "telescope.nvim" = telescope-nvim;
    # main-branch rewrite, same as the live install lazy was pulling: NvChad's
    # master-style ensure_installed is inert on it, and highlighting rides
    # neovim's bundled parsers — exact parity, revisit when NvChad catches up.
    "nvim-treesitter" = nvim-treesitter;
  };

  pluginFarm = pkgs.linkFarm "lazy-plugins"
    (lib.mapAttrsToList (name: path: { inherit name path; }) plugins);
in
{
  # NOT programs.neovim: the module generates its own init.lua, which would
  # conflict with the NvChad config tree linked below. Package only.
  home.packages = with pkgs; [
    neovim
    lua-language-server
    stylua
  ];

  home.sessionVariables.EDITOR = "nvim";
  home.shellAliases = {
    vim = "nvim";
    vi = "nvim";
  };

  # recursive (per-file links) so the generated module below can land inside
  # the same tree as the static config.
  xdg.configFile."nvim" = {
    source = ./nvim;
    recursive = true;
  };

  # The bridge between the two worlds: lua learns the store paths from here.
  xdg.configFile."nvim/lua/nix_paths.lua".text = ''
    -- generated by home/neovim.nix
    return {
      lazy = "${pkgs.vimPlugins.lazy-nvim}",
      plugins = "${pluginFarm}",
      gen = "${builtins.substring 0 8 (baseNameOf pluginFarm)}",
    }
  '';
}
