-- SbarLua entrypoint. `sbar` is deliberately a GLOBAL — every other file
-- uses it (the FelixKratz convention). colors.lua and settings.lua are
-- GENERATED by rice.nix from palette.nix; the files here are the static art.
sbar = require("sketchybar")

sbar.begin_config()
require("bar")
require("default")
require("items")
sbar.end_config()

sbar.event_loop()
