# TODO: convert this to yaml below
[windows]
gamer007 ansible_host=gamer007.localdomain ansible_user=your_username ansible_password=your_password
fafnir ansible_host=fafnir.localdomain ansible_user=your_username ansible_password=your_password
conan ansible_host=conan.localdomain ansible_user=your_username ansible_password=your_password

[homelab]
truenas ansible_host=truenas.localdomain ansible_user=your_username ansible_password=your_password
drogon ansible_host=drogon.localdomain ansible_user=your_username ansible_password=your_password

[all_servers:children]
homelab
windows
