# Development Tools - DevOps, containers, and cloud tools
tap "aws/tap"
tap "hashicorp/tap"
tap "johanhaleby/kubetail"
tap "keidarcy/tap"

brew "awscli"
brew "docker-compose"
brew "go"
brew "goreleaser"
brew "helm"
brew "helmfile"
brew "k9s"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "lazydocker"
brew "minikube"
brew "mkcert"
brew "saml2aws"
brew "skaffold"
brew "subversion"
brew "tilt"
brew "ttyd"
brew "aws/tap/copilot-cli"
brew "hashicorp/tap/terraform-ls"
brew "johanhaleby/kubetail/kubetail"
brew "keidarcy/tap/e1s"

# Development casks
cask "docker"
cask "insomnia"
cask "ngrok"
cask "postman"
cask "session-manager-plugin"
cask "requestly"