# Languages & Runtimes - Programming languages, databases, and runtime tools
brew "mise"
brew "ack"
brew "adns"
brew "openssl@3"
brew "icu4c@76"
brew "ant"
brew "eigen"
brew "foreman"
brew "libmagic"
brew "libpq"
brew "libidn2"
brew "litecli"
brew "lua-language-server"
brew "luarocks"
brew "mysql"
brew "netpbm"
brew "ollama"
brew "pdm"
brew "pigz"
brew "postgresql@14"
brew "python-tk@3.12"
brew "spim"

# Database and data tools casks
cask "dbvisualizer"
cask "postico"