# Security Tools - Penetration testing and security analysis
brew "aircrack-ng"
brew "binutils"
brew "binwalk"
brew "cifer"
brew "dns2tcp"
brew "fcrackzip"
brew "foremost"
brew "hashpump"
brew "hydra"
brew "john"
brew "knock"
brew "nmap"
brew "showkey"
brew "socat"
brew "tcpflow"
brew "tcpreplay"
brew "tcptrace"
brew "ucspi-tcp"

# Security-focused casks
cask "gpg-suite"
cask "little-snitch"
cask "micro-snitch"
cask "veracrypt"
cask "wireshark-chmodbpf"